version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  api:
    build: ./api
    expose:
      - ${API_SERVER_PORT}
    image: scottkey/whiskeynightapi:1.0.0
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && bundle exec rails s -p 9000 -e production"
    volumes:
    - .:/whiskeynight
    depends_on:
    - db
    links:
    - "db:database"
    ports:
    - "9000:9000"
  web:
    build: ./web
    image: scottkey/whiskeynightweb:1.0.0
    volumes:
    - .:/whiskeynight
    links:
    - api:api
    ports:
    - 80:80
    - 443:443
    depends_on:
    - api

