version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: 
      - .env
    environment: 
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 5
  api:
    build: ./api
    env_file: 
      - .env
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    image: scottkey/whiskeynightapi:1.0.0
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && bundle exec rails s -p ${API_SERVER_PORT} -e ${RAILS_ENV}"
    volumes:
      - .:/whiskeynight
    depends_on:
      - db
    links:
      - "db:database"

  web:
    build: ./web
    env_file: 
      - .env
    ports: 
      - ${WEB_APP_PORT}:${WEB_APP_ORIGIN}
    image: scottkey/whiskeynightweb:1.0.0
    volumes:
      - .:/whiskeynight
    links:
      - api
    depends_on:
      - api

