default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: -X3c*E@!zUjPiBcAcXRNV2g
  pool: 5

# everything below inherits  from default 
development:
  <<: *default
  database: whiskeynight_development
  
test:
  <<: *default
  database: whiskeynight_test

production:
  <<: *default
  database: whiskeynight_production
