default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

# everything below inherits  from default 
development:
  <<: *default
  database: whiskeynight_development
  
test:
  <<: *default
  database: whiskeynight_test

production:
  <<: *default
  database: whiskeynight_production
  host: db
 
